# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lotsman.v1 import lotsman_pb2 as lotsman_dot_v1_dot_lotsman__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lotsman/v1/lotsman_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LotsmanServiceStub(object):
    """Lotsman service is the in-container daemon RPC contract.
    Marina is the only expected client; gRPC over SSH-forwarded UDS.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_unary(
                '/lotsman.v1.LotsmanService/Run',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.RunRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.RunResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/lotsman.v1.LotsmanService/Status',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.StatusRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Kill = channel.unary_unary(
                '/lotsman.v1.LotsmanService/Kill',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.KillRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.KillResponse.FromString,
                _registered_method=True)
        self.Logs = channel.unary_unary(
                '/lotsman.v1.LotsmanService/Logs',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.LogsRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.LogsResponse.FromString,
                _registered_method=True)
        self.TailFollow = channel.unary_stream(
                '/lotsman.v1.LotsmanService/TailFollow',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.TailFollowRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.LogChunk.FromString,
                _registered_method=True)
        self.Whoami = channel.unary_unary(
                '/lotsman.v1.LotsmanService/Whoami',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.WhoamiRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.WhoamiResponse.FromString,
                _registered_method=True)
        self.Events = channel.unary_stream(
                '/lotsman.v1.LotsmanService/Events',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.EventsRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.Event.FromString,
                _registered_method=True)
        self.WatchdogList = channel.unary_unary(
                '/lotsman.v1.LotsmanService/WatchdogList',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.WatchdogListRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.WatchdogListResponse.FromString,
                _registered_method=True)
        self.WatchdogHistory = channel.unary_unary(
                '/lotsman.v1.LotsmanService/WatchdogHistory',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.WatchdogHistoryRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.WatchdogHistoryResponse.FromString,
                _registered_method=True)
        self.EventsHistoryAll = channel.unary_unary(
                '/lotsman.v1.LotsmanService/EventsHistoryAll',
                request_serializer=lotsman_dot_v1_dot_lotsman__pb2.EventsHistoryAllRequest.SerializeToString,
                response_deserializer=lotsman_dot_v1_dot_lotsman__pb2.EventsHistoryAllResponse.FromString,
                _registered_method=True)


class LotsmanServiceServicer(object):
    """Lotsman service is the in-container daemon RPC contract.
    Marina is the only expected client; gRPC over SSH-forwarded UDS.
    """

    def Run(self, request, context):
        """Run launches a script under the daemon's supervision and
        returns a jobId of the form `<hostId>/<ulid26>`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Status returns the current lifecycle state of a known job.
        Returns NOT_FOUND if jobId is unknown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Kill terminates a running job: SIGTERM, wait grace_sec, then SIGKILL.
        Idempotent on already-terminal jobs.
        Returns NOT_FOUND if jobId is unknown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logs(self, request, context):
        """Logs returns a snapshot of stdout/stderr for a job.
        Use TailFollow for live streaming.
        Returns NOT_FOUND if jobId is unknown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TailFollow(self, request, context):
        """TailFollow streams new stdout/stderr bytes as the job produces them,
        ending with a chunk where job_terminal=true once the job exits.
        Server-streaming RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Whoami(self, request, context):
        """Whoami returns the daemon's self-description: which tool image it lives
        in, defaults baked into manifest.toml, known pitfalls. Lets Marina probe
        a freshly-spawned host without out-of-band knowledge.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Events(self, request, context):
        """Events is a server-streaming RPC over watchdog hits + (later) state
        transitions. Setting `job_id` empty subscribes to all jobs on this
        Lotsman; `since_unix_ms` replays past events from history (0 = live only).
        The stream stays open until the client cancels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchdogList(self, request, context):
        """WatchdogList returns the set of watchdogs currently attached to a job
        (defaults from manifest plus any extras passed at Run-time), with
        their fired-once status. Returns NOT_FOUND if jobId is unknown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchdogHistory(self, request, context):
        """WatchdogHistory returns past fired events for a job — what crossed
        a threshold and when. Returns NOT_FOUND if jobId is unknown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventsHistoryAll(self, request, context):
        """EventsHistoryAll returns all events across every job on this Lotsman
        since `since_unix_ms`. Marina uses it to aggregate fan-out without
        needing to enumerate jobIds first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LotsmanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.RunRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.RunResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.StatusRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.StatusResponse.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.KillRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.KillResponse.SerializeToString,
            ),
            'Logs': grpc.unary_unary_rpc_method_handler(
                    servicer.Logs,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.LogsRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.LogsResponse.SerializeToString,
            ),
            'TailFollow': grpc.unary_stream_rpc_method_handler(
                    servicer.TailFollow,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.TailFollowRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.LogChunk.SerializeToString,
            ),
            'Whoami': grpc.unary_unary_rpc_method_handler(
                    servicer.Whoami,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.WhoamiRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.WhoamiResponse.SerializeToString,
            ),
            'Events': grpc.unary_stream_rpc_method_handler(
                    servicer.Events,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.EventsRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.Event.SerializeToString,
            ),
            'WatchdogList': grpc.unary_unary_rpc_method_handler(
                    servicer.WatchdogList,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.WatchdogListRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.WatchdogListResponse.SerializeToString,
            ),
            'WatchdogHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.WatchdogHistory,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.WatchdogHistoryRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.WatchdogHistoryResponse.SerializeToString,
            ),
            'EventsHistoryAll': grpc.unary_unary_rpc_method_handler(
                    servicer.EventsHistoryAll,
                    request_deserializer=lotsman_dot_v1_dot_lotsman__pb2.EventsHistoryAllRequest.FromString,
                    response_serializer=lotsman_dot_v1_dot_lotsman__pb2.EventsHistoryAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lotsman.v1.LotsmanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lotsman.v1.LotsmanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LotsmanService(object):
    """Lotsman service is the in-container daemon RPC contract.
    Marina is the only expected client; gRPC over SSH-forwarded UDS.
    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lotsman.v1.LotsmanService/Run',
            lotsman_dot_v1_dot_lotsman__pb2.RunRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lotsman.v1.LotsmanService/Status',
            lotsman_dot_v1_dot_lotsman__pb2.StatusRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lotsman.v1.LotsmanService/Kill',
            lotsman_dot_v1_dot_lotsman__pb2.KillRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.KillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lotsman.v1.LotsmanService/Logs',
            lotsman_dot_v1_dot_lotsman__pb2.LogsRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.LogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TailFollow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lotsman.v1.LotsmanService/TailFollow',
            lotsman_dot_v1_dot_lotsman__pb2.TailFollowRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.LogChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Whoami(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lotsman.v1.LotsmanService/Whoami',
            lotsman_dot_v1_dot_lotsman__pb2.WhoamiRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.WhoamiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Events(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lotsman.v1.LotsmanService/Events',
            lotsman_dot_v1_dot_lotsman__pb2.EventsRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchdogList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lotsman.v1.LotsmanService/WatchdogList',
            lotsman_dot_v1_dot_lotsman__pb2.WatchdogListRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.WatchdogListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchdogHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lotsman.v1.LotsmanService/WatchdogHistory',
            lotsman_dot_v1_dot_lotsman__pb2.WatchdogHistoryRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.WatchdogHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventsHistoryAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lotsman.v1.LotsmanService/EventsHistoryAll',
            lotsman_dot_v1_dot_lotsman__pb2.EventsHistoryAllRequest.SerializeToString,
            lotsman_dot_v1_dot_lotsman__pb2.EventsHistoryAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
